"""empty message

Revision ID: 97e33eead7ae
Revises: c8bc36bab404
Create Date: 2023-03-06 13:19:41.340977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e33eead7ae'
down_revision = 'c8bc36bab404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms_in_demand', schema=None) as batch_op:
        batch_op.drop_constraint('forms_in_demand_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_forms_in_demand', schema=None) as batch_op:
        batch_op.drop_constraint('user_forms_in_demand_forms_in_demand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forms_in_demand', ['forms_in_demand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_forms_in_demand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_forms_in_demand_forms_in_demand_id_fkey', 'user', ['forms_in_demand_id'], ['id'])

    with op.batch_alter_table('forms_in_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('forms_in_demand_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
