"""empty message

Revision ID: c8bc36bab404
Revises: d75ab73d8f02
Create Date: 2023-03-01 13:43:37.210893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bc36bab404'
down_revision = 'd75ab73d8f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_forms_in_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forms_in_demand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forms_in_demand_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms_in_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_demand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=700), nullable=True),
    sa.Column('residence', sa.String(length=700), nullable=True),
    sa.Column('experience', sa.String(length=700), nullable=True),
    sa.Column('moreinfo', sa.String(length=700), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_demand_id'], ['in_demand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms_in_demand')
    op.drop_table('in_demand')
    op.drop_table('user_forms_in_demand')
    # ### end Alembic commands ###
