"""empty message

Revision ID: d75ab73d8f02
Revises: cebdb321d124
Create Date: 2023-02-25 09:18:34.053637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75ab73d8f02'
down_revision = 'cebdb321d124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=700),
               existing_nullable=True)

    with op.batch_alter_table('establishment', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=700),
               existing_nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_profile_img',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=550),
               existing_nullable=True)
        batch_op.alter_column('event_portrait_img',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=550),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=700),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('event_portrait_img',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('event_profile_img',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('establishment', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
