"""empty message

Revision ID: e4c42e1efc06
Revises: 5467fcca080e
Create Date: 2023-02-17 17:14:09.844454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c42e1efc06'
down_revision = '5467fcca080e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('instrument_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_category_id'], ['instrument_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_profile_img', sa.String(length=255), nullable=True),
    sa.Column('band_portrait_img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('band_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('establishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_profile_img', sa.String(length=255), nullable=True),
    sa.Column('establishment_portrait_img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genre_band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_genre_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['music_genre_id'], ['music_genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genre_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_genre_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_genre_id'], ['music_genre.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('post_img', sa.String(length=255), nullable=True),
    sa.Column('post_video', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_profile_img', sa.String(length=255), nullable=True),
    sa.Column('event_portrait_img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genre_establishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_genre_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishment.id'], ),
    sa.ForeignKeyConstraint(['music_genre_id'], ['music_genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_genre_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_genre_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['music_genre_id'], ['music_genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('profile_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portrait_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('artistic_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('spotify_url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city_id')
        batch_op.drop_column('website_url')
        batch_op.drop_column('spotify_url')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('description')
        batch_op.drop_column('artistic_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('portrait_img')
        batch_op.drop_column('profile_img')
        batch_op.drop_column('user_name')

    op.drop_table('music_genre_event')
    op.drop_table('music_genre_establishment')
    op.drop_table('event')
    op.drop_table('comment')
    op.drop_table('user_instrument')
    op.drop_table('user_band')
    op.drop_table('post')
    op.drop_table('music_genre_user')
    op.drop_table('music_genre_band')
    op.drop_table('establishment')
    op.drop_table('band_instrument')
    op.drop_table('band')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('instrument')
    op.drop_table('music_genre')
    op.drop_table('instrument_category')
    op.drop_table('country')
    # ### end Alembic commands ###
